version: '3.1'

networks:
  my_network:
    driver: bridge


services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - my_network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - my_network
#
  service_metrics:
    build: .
    container_name: aiohttp-service-metric
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  grafana-storage: {}