version: "3"

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:7.3.2
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      GF_SECURITY_ADMIN_USER: admin_user
      GF_SECURITY_ADMIN_PASSWORD: admin_password
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: db:3306
      GF_DATABASE_NAME: grafana_db
      GF_DATABASE_USER: grafana_db_user
      GF_DATABASE_PASSWORD: grafana_password
    networks:
      grafana:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: grafana_password
      MYSQL_USER: grafana_db_user
      MYSQL_PASSWORD: grafana_password
      MYSQL_DATABASE: grafana_db
    ports:
      - "3306:3306"
    networks:
      grafana:
